// src/components/ui/Dialog.vue
<script setup lang="ts">
import { cn } from "@/lib/utils";
import { X } from "lucide-vue-next";
import { onBeforeUnmount, onMounted, ref, useId } from "vue";
import Button from "./Button.vue";

const FOCUSABLE =
  'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';

/**
 * Modal dialog: Escape and the scrim close it, Tab stays inside, and focus
 * returns to whatever opened it.
 */
const props = withDefaults(
  defineProps<{
    title: string;
    description?: string;
    /** False while an action is in flight that closing would orphan. */
    dismissible?: boolean;
    panelClass?: string;
  }>(),
  { dismissible: true },
);
const emit = defineEmits<{ close: [] }>();

const panelRef = ref<HTMLDivElement | null>(null);
const titleId = `dialog-title-${useId()}`;
const descriptionId = `dialog-desc-${useId()}`;
let opener: HTMLElement | null = null;

function onKey(event: KeyboardEvent): void {
  if (event.key === "Escape" && props.dismissible) {
    event.stopPropagation();
    emit("close");
    return;
  }
  const panel = panelRef.value;
  if (event.key !== "Tab" || !panel) return;
  const focusable = Array.from(panel.querySelectorAll<HTMLElement>(FOCUSABLE));
  if (focusable.length === 0) return;
  const first = focusable[0];
  const last = focusable[focusable.length - 1];
  if (event.shiftKey && document.activeElement === first) {
    event.preventDefault();
    last?.focus();
  } else if (!event.shiftKey && document.activeElement === last) {
    event.preventDefault();
    first?.focus();
  }
}

onMounted(() => {
  opener = document.activeElement as HTMLElement | null;
  const panel = panelRef.value;
  const first = panel?.querySelector<HTMLElement>("[data-autofocus]") ?? panel?.querySelector<HTMLElement>(FOCUSABLE);
  (first ?? panel)?.focus();
  document.addEventListener("keydown", onKey, true);
});
onBeforeUnmount(() => {
  document.removeEventListener("keydown", onKey, true);
  opener?.focus?.();
});

function onScrimClick(event: MouseEvent): void {
  if (event.target === event.currentTarget && props.dismissible) emit("close");
}
</script>

<template>
  <Teleport to="body">
    <div
      class="no-drag fixed inset-0 z-modal flex animate-scrim-in items-center justify-center bg-black/45 p-6 backdrop-blur-[2px]"
      @mousedown="onScrimClick"
    >
      <div
        ref="panelRef"
        role="dialog"
        aria-modal="true"
        :aria-labelledby="titleId"
        :aria-describedby="description || $slots.description ? descriptionId : undefined"
        tabindex="-1"
        :class="
          cn(
            'flex max-h-[88vh] w-[30rem] max-w-full animate-dialog-in flex-col rounded-lg bg-card text-card-foreground shadow-dialog outline-none',
            panelClass,
          )
        "
      >
        <div class="flex items-start justify-between gap-4 px-5 pb-3 pt-4">
          <div class="min-w-0">
            <h2 :id="titleId" class="text-lg font-semibold">{{ title }}</h2>
            <p v-if="description || $slots.description" :id="descriptionId" class="mt-0.5 text-sm text-muted-foreground">
              <slot name="description">{{ description }}</slot>
            </p>
          </div>
          <Button v-if="dismissible" variant="ghost" size="icon-sm" aria-label="Close" class="-mr-1.5" @click="emit('close')">
            <X />
          </Button>
        </div>
        <div v-if="$slots.default" class="min-h-0 flex-1 overflow-y-auto px-5 pb-4">
          <slot />
        </div>
        <div v-if="$slots.footer" class="flex items-center justify-end gap-2 border-t px-5 py-3">
          <slot name="footer" />
        </div>
      </div>
    </div>
  </Teleport>
</template>

// src/components/ui/Dialog.tsx
import { cn } from "@/lib/utils";
import { X } from "lucide-react";
import { type ReactNode, useEffect, useId, useRef } from "react";
import { Button } from "./primitives";

const FOCUSABLE =
  'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';

/**
 * Modal dialog: Escape and the scrim close it, Tab stays inside, and focus
 * returns to whatever opened it.
 */
export function Dialog({
  title,
  description,
  onClose,
  children,
  footer,
  className,
  dismissible = true,
}: {
  title: ReactNode;
  description?: ReactNode;
  onClose: () => void;
  children?: ReactNode;
  footer?: ReactNode;
  className?: string;
  /** False while an action is in flight that closing would orphan. */
  dismissible?: boolean;
}) {
  const panelRef = useRef<HTMLDivElement>(null);
  const titleId = useId();
  const descriptionId = useId();
  const closeRef = useRef(onClose);
  closeRef.current = onClose;
  const dismissibleRef = useRef(dismissible);
  dismissibleRef.current = dismissible;

  useEffect(() => {
    const opener = document.activeElement as HTMLElement | null;
    const panel = panelRef.current;
    const first = panel?.querySelector<HTMLElement>("[data-autofocus]") ?? panel?.querySelector<HTMLElement>(FOCUSABLE);
    (first ?? panel)?.focus();

    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape" && dismissibleRef.current) {
        event.stopPropagation();
        closeRef.current();
        return;
      }
      if (event.key !== "Tab" || !panel) return;
      const focusable = Array.from(panel.querySelectorAll<HTMLElement>(FOCUSABLE));
      if (focusable.length === 0) return;
      const firstEl = focusable[0];
      const lastEl = focusable[focusable.length - 1];
      if (event.shiftKey && document.activeElement === firstEl) {
        event.preventDefault();
        lastEl?.focus();
      } else if (!event.shiftKey && document.activeElement === lastEl) {
        event.preventDefault();
        firstEl?.focus();
      }
    };
    document.addEventListener("keydown", onKey, true);
    return () => {
      document.removeEventListener("keydown", onKey, true);
      opener?.focus?.();
    };
  }, []);

  return (
    <div
      className="no-drag fixed inset-0 z-50 flex animate-scrim-in items-center justify-center bg-[hsl(230_20%_6%/0.42)] p-6 backdrop-blur-[2px]"
      onMouseDown={(e) => {
        if (e.target === e.currentTarget && dismissible) onClose();
      }}
    >
      <div
        ref={panelRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={description ? descriptionId : undefined}
        tabIndex={-1}
        className={cn(
          "flex max-h-[88vh] w-[30rem] max-w-full animate-dialog-in flex-col rounded-xl bg-card text-card-foreground shadow-dialog outline-none",
          className,
        )}
      >
        <div className="flex items-start justify-between gap-4 px-5 pb-3 pt-4">
          <div className="min-w-0">
            <h2 id={titleId} className="text-lg font-semibold">
              {title}
            </h2>
            {description && (
              <p id={descriptionId} className="mt-0.5 text-sm text-muted-foreground">
                {description}
              </p>
            )}
          </div>
          {dismissible && (
            <Button variant="ghost" size="icon-sm" onClick={onClose} aria-label="Close" className="-mr-1.5">
              <X />
            </Button>
          )}
        </div>
        {children && <div className="min-h-0 flex-1 overflow-y-auto px-5 pb-4">{children}</div>}
        {footer && <div className="flex items-center justify-end gap-2 border-t px-5 py-3">{footer}</div>}
      </div>
    </div>
  );
}

/** Yes/no for destructive actions, in place of window.confirm. */
export function ConfirmDialog({
  title,
  children,
  confirmLabel,
  onConfirm,
  onCancel,
  busy = false,
}: {
  title: string;
  children: ReactNode;
  confirmLabel: string;
  onConfirm: () => void;
  onCancel: () => void;
  busy?: boolean;
}) {
  return (
    <Dialog
      title={title}
      onClose={onCancel}
      dismissible={!busy}
      className="w-[26rem]"
      footer={
        <>
          <Button variant="secondary" onClick={onCancel} disabled={busy}>
            Cancel
          </Button>
          <Button variant="danger" onClick={onConfirm} loading={busy} data-autofocus>
            {confirmLabel}
          </Button>
        </>
      }
    >
      <div className="text-base text-muted-foreground">{children}</div>
    </Dialog>
  );
}
