// src/components/ui/Popover.vue
<script setup lang="ts">
import { cn } from "@/lib/utils";
import { onBeforeUnmount, ref, watch } from "vue";

/** A panel anchored under its trigger; outside clicks and Escape close it. */
const props = defineProps<{ open: boolean; label: string; panelClass?: string }>();
const emit = defineEmits<{ close: [] }>();
const rootRef = ref<HTMLDivElement | null>(null);

function onPointer(event: MouseEvent): void {
  if (!rootRef.value?.contains(event.target as Node)) emit("close");
}
function onKey(event: KeyboardEvent): void {
  if (event.key === "Escape") emit("close");
}

watch(
  () => props.open,
  (open) => {
    if (open) {
      document.addEventListener("mousedown", onPointer);
      document.addEventListener("keydown", onKey);
    } else {
      document.removeEventListener("mousedown", onPointer);
      document.removeEventListener("keydown", onKey);
    }
  },
);
onBeforeUnmount(() => {
  document.removeEventListener("mousedown", onPointer);
  document.removeEventListener("keydown", onKey);
});
</script>

<template>
  <div ref="rootRef" class="relative">
    <slot name="trigger" />
    <Transition name="popover-pop">
      <div
        v-if="open"
        role="dialog"
        :aria-label="label"
        :class="cn('absolute right-0 top-full z-overlay mt-1.5 w-[22rem] rounded-lg bg-card p-4 shadow-dialog', panelClass)"
      >
        <slot />
      </div>
    </Transition>
  </div>
</template>

// src/components/ui/Popover.tsx
import { cn } from "@/lib/utils";
import { type ReactNode, useEffect, useRef } from "react";

/** A panel anchored under its trigger; outside clicks and Escape close it. */
export function Popover({
  open,
  onClose,
  trigger,
  children,
  className,
  label,
}: {
  open: boolean;
  onClose: () => void;
  trigger: ReactNode;
  children: ReactNode;
  className?: string;
  label: string;
}) {
  const rootRef = useRef<HTMLDivElement>(null);
  const closeRef = useRef(onClose);
  closeRef.current = onClose;

  useEffect(() => {
    if (!open) return;
    const onPointer = (event: MouseEvent) => {
      if (!rootRef.current?.contains(event.target as Node)) closeRef.current();
    };
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") closeRef.current();
    };
    document.addEventListener("mousedown", onPointer);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onPointer);
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);

  return (
    <div ref={rootRef} className="relative">
      {trigger}
      {open && (
        <div
          role="dialog"
          aria-label={label}
          className={cn(
            "absolute right-0 top-full z-40 mt-1.5 w-[22rem] animate-dialog-in rounded-xl bg-card p-4 shadow-dialog",
            className,
          )}
        >
          {children}
        </div>
      )}
    </div>
  );
}
